In [1]:
import sys
lst=[10,20,30]
print("content of lst=",lst)
print("Memory space of lst=",sys.getsizeof(lst))

content of lst= [10, 20, 30]
Memory space of lst= 88


In [2]:
#Convert Traditioanl Python List into ndarray object
import numpy as np
a=np.array(lst)
print("Content of ndarray=",a)
print("Memory Space of ndarray=",sys.getsizeof(a))

Content of ndarray= [10 20 30]
Memory Space of ndarray= 124


In [3]:
lst=[10,20,30,123,45,67,88,99,34,123,56,78]
print("content of lst=",lst)
print("Memory space of lst=",sys.getsizeof(lst))

content of lst= [10, 20, 30, 123, 45, 67, 88, 99, 34, 123, 56, 78]
Memory space of lst= 152


In [4]:
a=np.array(lst)
print("Content of ndarray=",a)
print("type of a=",type(a))
print("Memory Space of ndarray=",sys.getsizeof(a))

Content of ndarray= [ 10  20  30 123  45  67  88  99  34 123  56  78]
type of a= <class 'numpy.ndarray'>
Memory Space of ndarray= 160


In [5]:
lst=[10,20,30,123,45,67,88,99,34,123,56,78,123,45,67,88,99,34,123,56,78,99,34,123,56,78,123,45]
print("content of lst=",lst)
print("Memory space of lst=",sys.getsizeof(lst))

content of lst= [10, 20, 30, 123, 45, 67, 88, 99, 34, 123, 56, 78, 123, 45, 67, 88, 99, 34, 123, 56, 78, 99, 34, 123, 56, 78, 123, 45]
Memory space of lst= 280


In [6]:
a=np.array(lst)
print("Content of ndarray=",a)
print("type of a=",type(a))
print("Memory Space of ndarray=",sys.getsizeof(a))

Content of ndarray= [ 10  20  30 123  45  67  88  99  34 123  56  78 123  45  67  88  99  34
 123  56  78  99  34 123  56  78 123  45]
type of a= <class 'numpy.ndarray'>
Memory Space of ndarray= 224


In [7]:
#2 Difference
lst=[10,20,30,40,50,60,70,80]
print("content of List=",lst)
print("Memory Address=",id(lst))

content of List= [10, 20, 30, 40, 50, 60, 70, 80]
Memory Address= 2892125280832


In [10]:
for val in lst:
    print("{}---->{}--->{}".format(val,id(val),id(lst)))

10---->140726482289736--->2892125280832
20---->140726482290056--->2892125280832
30---->140726482290376--->2892125280832
40---->140726482290696--->2892125280832
50---->140726482291016--->2892125280832
60---->140726482291336--->2892125280832
70---->140726482291656--->2892125280832
80---->140726482291976--->2892125280832


In [13]:
a=np.array(lst)
print("content of ndarray=",a)
print("Memory Address=",id(a))

content of ndarray= [10 20 30 40 50 60 70 80]
Memory Address= 2892123579824


In [15]:
for val in a:
    print("{}--->{}--->{}".format(val,id(val),id(a)))
    
    

10--->2892127300080--->2892123579824
20--->2892127300336--->2892123579824
30--->2892127294096--->2892123579824
40--->2892127299728--->2892123579824
50--->2892127300080--->2892123579824
60--->2892127294096--->2892123579824
70--->2892127299728--->2892123579824
80--->2892127300080--->2892123579824


In [16]:
#3rd Difference--Vector Based Operation
lst=[10,20,30]
lst1=[]
for val in lst:
    lst1.append(val+1)
print("Content of lst=",lst)
print("Content of lst1=",lst1)
    


Content of lst= [10, 20, 30]
Content of lst1= [11, 21, 31]


In [17]:
lst=[10,20,30]
lst=lst+1  # TypeError: can only concatenate list (not "int") to list
#here Vector Based Operation is not Possible to perform on List object

TypeError: can only concatenate list (not "int") to list

In [20]:
lst=[10,20,30]
a=np.array(lst)
print("original content of a =",a)
a=a+1 # Vector Based Operation
print("Updated Content of a=",a)

original content of a = [10 20 30]
Updated Content of a= [11 21 31]


In [21]:
lst=[10,-20,30,-45,67,-34]
#lst>0--Vector Based Operation Not Possible

TypeError: '>' not supported between instances of 'list' and 'int'

In [22]:
lst=[10,-20,30,-45,67,-34]
a=np.array(lst)
print(a,type(a))


[ 10 -20  30 -45  67 -34] <class 'numpy.ndarray'>


In [24]:
a[a>0]

array([10, 30, 67])

In [25]:
a[a<0]

array([-20, -45, -34])

In [26]:
lst=[10,20,30,123,45,67,88,99,34,123,56,78,123,45,67,88,99,34,123,56,78,99,34,123,56,78,123,45]
print("content of lst=",lst)
print("Memory space of lst=",sys.getsizeof(lst))

content of lst= [10, 20, 30, 123, 45, 67, 88, 99, 34, 123, 56, 78, 123, 45, 67, 88, 99, 34, 123, 56, 78, 99, 34, 123, 56, 78, 123, 45]
Memory space of lst= 280


In [27]:
a=np.array(lst)
a

array([ 10,  20,  30, 123,  45,  67,  88,  99,  34, 123,  56,  78, 123,
        45,  67,  88,  99,  34, 123,  56,  78,  99,  34, 123,  56,  78,
       123,  45])

In [28]:
lst=[10,"Rossum",34.56,True,2+3j]
print(lst,type(lst))

[10, 'Rossum', 34.56, True, (2+3j)] <class 'list'>


In [29]:
for val in lst:
    print(val,"--->",type(val))

10 ---> <class 'int'>
Rossum ---> <class 'str'>
34.56 ---> <class 'float'>
True ---> <class 'bool'>
(2+3j) ---> <class 'complex'>


In [30]:
lst=[10,"Rossum",34.56,True,2+3j]
print(lst,type(lst))

[10, 'Rossum', 34.56, True, (2+3j)] <class 'list'>


In [31]:
a=np.array(lst)
print(a,type(a))

['10' 'Rossum' '34.56' 'True' '(2+3j)'] <class 'numpy.ndarray'>


In [33]:
lst=[10,20,30,True,12.34]
print(lst,type(lst))

[10, 20, 30, True, 12.34] <class 'list'>


In [34]:
a=np.array(lst)
print(a,type(a))

[10.   20.   30.    1.   12.34] <class 'numpy.ndarray'>


In [35]:
lst=[10,"Rossum",34.56,True,2+3j]
print(lst,type(lst))
a=np.array(lst,dtype=object)
print(a,type(a))

[10, 'Rossum', 34.56, True, (2+3j)] <class 'list'>
[10 'Rossum' 34.56 True (2+3j)] <class 'numpy.ndarray'>


In [36]:
for val in a:
    print(val,type(val))

10 <class 'int'>
Rossum <class 'str'>
34.56 <class 'float'>
True <class 'bool'>
(2+3j) <class 'complex'>
