In [1]:
import numpy as np


In [2]:
lst=[10,20,30,40,50,60,70,80,90]
print(lst,type(lst))

[10, 20, 30, 40, 50, 60, 70, 80, 90] <class 'list'>


In [3]:
#Convert list object into ndarray object.
a=np.array(lst)
print(a,type(a))

[10 20 30 40 50 60 70 80 90] <class 'numpy.ndarray'>


In [4]:
a

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [5]:
#Find the dimension of an array--we use 'ndim' attribute of ndarray object
print("Dimension of a=",a.ndim)


Dimension of a= 1


In [6]:
#Find the Shape of ndarray by using shape attribute
print("Shape of ndarray=",a.shape)

Shape of ndarray= (9,)


In [7]:
#Find Size of ndarray  by using size attribute
print("Number of Elements in ndarray=",a.size)

Number of Elements in ndarray= 9


In [8]:
#Find Size of ndarray  by using len()
print("Number of Elements in ndarray=",len(a))

Number of Elements in ndarray= 9


In [9]:
#Find data type of ndarray (Type of Data) obtained by using dtype attribute
print("Data type of ndarray internally=",a.dtype)

Data type of ndarray internally= int32


In [10]:
#Here attrubutes of ndarray are ndim,shape,size,dtype

In [11]:
lst=[10,20,30,40,50,60,70,80,90]
print(lst,type(lst))

[10, 20, 30, 40, 50, 60, 70, 80, 90] <class 'list'>


In [12]:
#Here we are reshaping the ndarray object
a=np.array(lst)
print(a,type(a))

[10 20 30 40 50 60 70 80 90] <class 'numpy.ndarray'>


In [13]:
#To reshape the ndarray object as matrix, we have Two Approaches
# 1. By using  shape Attribute
# 2. By using reshape() Function

In [14]:
# 1. By using  shape Attribute
# Syntax:  ndarrayobject.shape=(Rows,Cols)

In [15]:
lst=[10,20,30,40,50,60,70,80,90]
a=np.array(lst)
print(a,type(a))

[10 20 30 40 50 60 70 80 90] <class 'numpy.ndarray'>


In [16]:
a.shape=(3,3)
print(a,type(a))

[[10 20 30]
 [40 50 60]
 [70 80 90]] <class 'numpy.ndarray'>


In [17]:
print("Dimension of ndarray a=",a.ndim)
print("Shape of ndarray a=",a.shape)
print("Size of ndarray a=",a.size)
print("Data Type of ndarray=",a.dtype)

Dimension of ndarray a= 2
Shape of ndarray a= (3, 3)
Size of ndarray a= 9
Data Type of ndarray= int32


In [18]:
lst=[10,20,30,40,50,60,70,80,90,25,35,15]
print(lst,type(lst))

[10, 20, 30, 40, 50, 60, 70, 80, 90, 25, 35, 15] <class 'list'>


In [19]:
a=np.array(lst)
print(a,type(a))

[10 20 30 40 50 60 70 80 90 25 35 15] <class 'numpy.ndarray'>


In [21]:
#a.shape=(4,5)----ValueError: cannot reshape array of size 12 into shape (4,5)

In [23]:
a.shape=(3,4)
print("Content of ndarray a=")
print(a)
print("Dimension of ndarray a=",a.ndim)
print("Shape of ndarray a=",a.shape)
print("Size of ndarray a=",a.size)
print("Data Type of ndarray=",a.dtype)

Content of ndarray a=
[[10 20 30 40]
 [50 60 70 80]
 [90 25 35 15]]
Dimension of ndarray a= 2
Shape of ndarray a= (3, 4)
Size of ndarray a= 12
Data Type of ndarray= int32


In [24]:
a.shape=(4,3)
print("Content of ndarray a=")
print(a)
print("Dimension of ndarray a=",a.ndim)
print("Shape of ndarray a=",a.shape)
print("Size of ndarray a=",a.size)
print("Data Type of ndarray=",a.dtype)

Content of ndarray a=
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [25 35 15]]
Dimension of ndarray a= 2
Shape of ndarray a= (4, 3)
Size of ndarray a= 12
Data Type of ndarray= int32


In [25]:
a.shape=(6,2)
print("Content of ndarray a=")
print(a)
print("Dimension of ndarray a=",a.ndim)
print("Shape of ndarray a=",a.shape)
print("Size of ndarray a=",a.size)
print("Data Type of ndarray=",a.dtype)

Content of ndarray a=
[[10 20]
 [30 40]
 [50 60]
 [70 80]
 [90 25]
 [35 15]]
Dimension of ndarray a= 2
Shape of ndarray a= (6, 2)
Size of ndarray a= 12
Data Type of ndarray= int32


In [26]:
a.shape=(2,6)
print("Content of ndarray a=")
print(a)
print("Dimension of ndarray a=",a.ndim)
print("Shape of ndarray a=",a.shape)
print("Size of ndarray a=",a.size)
print("Data Type of ndarray=",a.dtype)

Content of ndarray a=
[[10 20 30 40 50 60]
 [70 80 90 25 35 15]]
Dimension of ndarray a= 2
Shape of ndarray a= (2, 6)
Size of ndarray a= 12
Data Type of ndarray= int32


In [27]:
a.shape=(12,1)
print("Content of ndarray a=")
print(a)
print("Dimension of ndarray a=",a.ndim)
print("Shape of ndarray a=",a.shape)
print("Size of ndarray a=",a.size)
print("Data Type of ndarray=",a.dtype)

Content of ndarray a=
[[10]
 [20]
 [30]
 [40]
 [50]
 [60]
 [70]
 [80]
 [90]
 [25]
 [35]
 [15]]
Dimension of ndarray a= 2
Shape of ndarray a= (12, 1)
Size of ndarray a= 12
Data Type of ndarray= int32


In [28]:
a.shape=(1,12)
print("Content of ndarray a=")
print(a)
print("Dimension of ndarray a=",a.ndim)
print("Shape of ndarray a=",a.shape)
print("Size of ndarray a=",a.size)
print("Data Type of ndarray=",a.dtype)

Content of ndarray a=
[[10 20 30 40 50 60 70 80 90 25 35 15]]
Dimension of ndarray a= 2
Shape of ndarray a= (1, 12)
Size of ndarray a= 12
Data Type of ndarray= int32


In [29]:
a.shape=(12,) # Making 2d array as 1d array
print("Content of ndarray a=")
print(a)
print("Dimension of ndarray a=",a.ndim)
print("Shape of ndarray a=",a.shape)
print("Size of ndarray a=",a.size)
print("Data Type of ndarray=",a.dtype)

Content of ndarray a=
[10 20 30 40 50 60 70 80 90 25 35 15]
Dimension of ndarray a= 1
Shape of ndarray a= (12,)
Size of ndarray a= 12
Data Type of ndarray= int32


In [30]:
a.shape=(2,3,2) #Converting 1darray into 3darray
print("Content of ndarray a=")
print(a)
print("Dimension of ndarray a=",a.ndim)
print("Shape of ndarray a=",a.shape)
print("Size of ndarray a=",a.size)
print("Data Type of ndarray=",a.dtype)

Content of ndarray a=
[[[10 20]
  [30 40]
  [50 60]]

 [[70 80]
  [90 25]
  [35 15]]]
Dimension of ndarray a= 3
Shape of ndarray a= (2, 3, 2)
Size of ndarray a= 12
Data Type of ndarray= int32


In [32]:
## 2. By using reshape() Function
#here reshape() present in ndarray object

In [34]:
lst=[10,20,30,40,50,60]
print(lst,type(lst))

[10, 20, 30, 40, 50, 60] <class 'list'>


In [36]:
a=np.array(lst)
print(a,type(a))

[10 20 30 40 50 60] <class 'numpy.ndarray'>


In [37]:
a.reshape(2,3)

array([[10, 20, 30],
       [40, 50, 60]])

In [38]:
print(a)

[10 20 30 40 50 60]


In [39]:
a=a.reshape(2,3)
print(a)

[[10 20 30]
 [40 50 60]]


In [40]:
a

array([[10, 20, 30],
       [40, 50, 60]])

In [41]:
print("Content of ndarray a=")
print(a)
print("Dimension of ndarray a=",a.ndim)
print("Shape of ndarray a=",a.shape)
print("Size of ndarray a=",a.size)
print("Data Type of ndarray=",a.dtype)

Content of ndarray a=
[[10 20 30]
 [40 50 60]]
Dimension of ndarray a= 2
Shape of ndarray a= (2, 3)
Size of ndarray a= 6
Data Type of ndarray= int32


In [42]:
a=a.reshape(3,2)
print("Content of ndarray a=")
print(a)
print("Dimension of ndarray a=",a.ndim)
print("Shape of ndarray a=",a.shape)
print("Size of ndarray a=",a.size)
print("Data Type of ndarray=",a.dtype)

Content of ndarray a=
[[10 20]
 [30 40]
 [50 60]]
Dimension of ndarray a= 2
Shape of ndarray a= (3, 2)
Size of ndarray a= 6
Data Type of ndarray= int32


In [43]:
lst=[10,20,30,40,50,60,70,80,90,15,25,35,55,65,75,85]
print(lst,type(lst))
len(lst)

[10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 25, 35, 55, 65, 75, 85] <class 'list'>


16

In [44]:
a=np.array(lst)
print("Content of ndarray a=")
print(a)
print("Dimension of ndarray a=",a.ndim)
print("Shape of ndarray a=",a.shape)
print("Size of ndarray a=",a.size)
print("Data Type of ndarray=",a.dtype)

Content of ndarray a=
[10 20 30 40 50 60 70 80 90 15 25 35 55 65 75 85]
Dimension of ndarray a= 1
Shape of ndarray a= (16,)
Size of ndarray a= 16
Data Type of ndarray= int32


In [45]:
#Conver ndarray Dimension as 3d
a.shape=(2,4,2)
print("Content of ndarray a=")
print(a)
print("Dimension of ndarray a=",a.ndim)
print("Shape of ndarray a=",a.shape)
print("Size of ndarray a=",a.size)
print("Data Type of ndarray=",a.dtype)

Content of ndarray a=
[[[10 20]
  [30 40]
  [50 60]
  [70 80]]

 [[90 15]
  [25 35]
  [55 65]
  [75 85]]]
Dimension of ndarray a= 3
Shape of ndarray a= (2, 4, 2)
Size of ndarray a= 16
Data Type of ndarray= int32


In [46]:
#Conver ndarray Dimension as 4-D
a.shape=(2,2,2,2)
print("Content of ndarray a=")
print(a)
print("Dimension of ndarray a=",a.ndim)
print("Shape of ndarray a=",a.shape)
print("Size of ndarray a=",a.size)
print("Data Type of ndarray=",a.dtype)

Content of ndarray a=
[[[[10 20]
   [30 40]]

  [[50 60]
   [70 80]]]


 [[[90 15]
   [25 35]]

  [[55 65]
   [75 85]]]]
Dimension of ndarray a= 4
Shape of ndarray a= (2, 2, 2, 2)
Size of ndarray a= 16
Data Type of ndarray= int32


In [47]:
import math
math.sin(90)

0.8939966636005579

In [49]:
math.cos(0)

1.0

In [50]:
math.sin(90)==math.cos(0)

False